export type WorkforceNodeType = 'ROOT' | 'ORCHESTRATOR' | 'PILLAR' | 'DEPARTMENT' | 'AI_AGENT' | 'HUMAN_EMPLOYEE' | 'TOOL' | 'WORKFLOW';

export interface WorkforceTreeNode {
  id: string;
  name: string;
  title: string;
  role: string;
  type: WorkforceNodeType;
  category: 'ORCHESTREE' | 'AI' | 'HUMAN' | 'ECOSYSTEM';
  department?: 'EXECUTIVE' | 'MARKETING' | 'SALES' | 'FINANCE' | 'HR' | 'OPERATIONS' | 'CREATIVE' | 'TECH' | 'DATA';
  avatarEmoji?: string;
  status: 'ACTIVE' | 'AUTOPILOT' | 'PAIRED' | 'ORCHESTRATING' | 'READY';
  score?: number;
  workingHours?: string;
  partnerId?: string;
  partnerName?: string;
  connectedTools?: string[];
  currentTask?: string;
  skills?: string[];
  responsibilities?: string[];
  children?: WorkforceTreeNode[];
  description?: string;
  level: number;
}

export const WORKFORCE_TREE_DATA: WorkforceTreeNode = {
  id: 'root-orchestree',
  name: 'OrchestreeAI',
  title: 'AI Workforce Operating System',
  role: 'Workforce OS Root',
  type: 'ROOT',
  category: 'ORCHESTREE',
  level: 0,
  avatarEmoji: '🌳',
  status: 'ORCHESTRATING',
  score: 99,
  workingHours: '24/7 Enterprise OS',
  description: 'Lapisan fondasi sistem operasi yang menghubungkan seluruh staf manusia, AI agent otonom, data perusahaan, dan workflow.',
  connectedTools: ['Multi-LLM Kernel', 'Postgres Vector DB', 'Model Router DAG', 'Enterprise RBAC'],
  skills: ['Workforce Governance', 'SLA Orchestration', 'Tenant Isolation', 'Zero-Trust Security'],
  responsibilities: ['Menjaga kestabilan ekosistem kerja', 'Sinkronisasi state lintas departemen', 'Audit log tamper-proof'],
  children: [
    {
      id: 'node-cos-arya',
      name: 'Arya',
      title: 'AI Chief of Staff',
      role: 'Executive Intelligence & Multi-Agent Orchestrator',
      type: 'ORCHESTRATOR',
      category: 'ORCHESTREE',
      department: 'EXECUTIVE',
      level: 1,
      avatarEmoji: '👑',
      status: 'ORCHESTRATING',
      score: 98,
      workingHours: '08:00 - 20:00 WIB',
      partnerId: 'human-ceo-budi',
      partnerName: 'Budi Santoso (CEO / Founder)',
      description: 'Pusat komando orkestrasi yang mendelegasikan sasaran bisnis strategis ke seluruh AI specialist dan mengoordinasikan persetujuan manusia.',
      connectedTools: ['WhatsApp Gateway', 'Executive Cockpit', 'Company Brain', 'Trello API', 'Slack'],
      currentTask: 'Dekomposisi sasaran ekspansi Q3 & orkestrasi 16 AI agen spesialis',
      skills: ['Goal Decomposition', 'Cross-Agent Delegation', 'Executive Reporting', 'Decision Tracking', 'SLA Governance'],
      responsibilities: [
        'Memecah target bisnis menjadi rencana kerja terukur',
        'Mendelegasikan tugas ke AI Agent departemen terkait',
        'Menyusun executive briefing harian untuk pimpinan',
        'Meminta persetujuan manusia untuk aksi berisiko tinggi',
      ],
      children: [
        // ======================== PILLAR 1: AI WORKFORCE ========================
        {
          id: 'pillar-ai-workforce',
          name: 'AI Workforce Layer',
          title: 'Specialized Autonomous Agents',
          role: 'AI Workforce Division',
          type: 'PILLAR',
          category: 'AI',
          level: 2,
          avatarEmoji: '🤖',
          status: 'ACTIVE',
          score: 98,
          description: 'Kumpulan 16+ AI Agent spesialis yang bekerja otonom sesuai SOP divisi dengan pengawasan ketat.',
          skills: ['Autonomous Execution', '24/7 Autopilot', 'SOP Compliance', 'Continuous Learning'],
          children: [
            // Marketing Branch
            {
              id: 'dept-ai-marketing',
              name: 'AI Marketing & Growth',
              title: 'Marketing Department (AI)',
              role: 'Marketing AI Division',
              type: 'DEPARTMENT',
              category: 'AI',
              department: 'MARKETING',
              level: 3,
              avatarEmoji: '🚀',
              status: 'ACTIVE',
              score: 97,
              partnerId: 'dept-human-marketing',
              partnerName: 'Tim Human Marketing',
              description: 'Divisi pemasaran bertenaga AI untuk perencanaan kampanye, penulisan copy persuasif, dan optimasi konversi.',
              children: [
                {
                  id: 'agent-kirana-mkt',
                  name: 'Kirana',
                  title: 'AI Marketing Strategist',
                  role: 'Campaign & Audience Planning Specialist',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'MARKETING',
                  level: 4,
                  avatarEmoji: '🎯',
                  status: 'ACTIVE',
                  score: 96,
                  workingHours: '08:00 - 18:00 WIB',
                  partnerId: 'human-maya-mkt',
                  partnerName: 'Maya Wulandari (Marketing Director)',
                  connectedTools: ['Meta Ads Manager', 'Google Analytics 4', 'Instagram Graph API', 'WhatsApp'],
                  currentTask: 'Optimasi performa kampanye Omnichannel Q3 & alokasi budget ROAS',
                  skills: ['GTM Strategy', 'Funnel Analytics', 'Audience Segmentation', 'Omnichannel Scheduling'],
                  responsibilities: ['Penyusunan strategi kampanye', 'Analisis tren pasar & audiens', 'Pelaporan mingguan'],
                },
                {
                  id: 'agent-reza-copy',
                  name: 'Reza Copy',
                  title: 'AI Persuasive Copywriter',
                  role: 'Direct Response Copywriting Specialist',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'MARKETING',
                  level: 4,
                  avatarEmoji: '✍️',
                  status: 'ACTIVE',
                  score: 97,
                  workingHours: '08:00 - 18:00 WIB',
                  partnerId: 'human-content-staff',
                  partnerName: 'Content Marketing Staff',
                  connectedTools: ['Google Docs', 'Telegram', 'WordPress', 'Instagram'],
                  currentTask: 'Sintesis 12 caption Instagram & 3 naskah video TikTok bahasa Indonesia natural',
                  skills: ['Direct Response Copywriting', 'SEO Copywriting', 'Storytelling', 'Headline Hook Matrix'],
                  responsibilities: ['Penulisan caption harian', 'Naskah video promosi', 'Email newsletter'],
                },
                {
                  id: 'agent-siti-social',
                  name: 'Siti Social',
                  title: 'AI Social Media Scheduler',
                  role: 'Multi-Channel Dispatch & Community Agent',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'MARKETING',
                  level: 4,
                  avatarEmoji: '📱',
                  status: 'AUTOPILOT',
                  score: 99,
                  workingHours: '24/7 Autopilot',
                  partnerId: 'human-maya-mkt',
                  partnerName: 'Maya Wulandari (Marketing Director)',
                  connectedTools: ['Instagram', 'TikTok', 'LinkedIn', 'Facebook', 'X / Twitter'],
                  currentTask: 'Menjadwalkan penerbitan otomatis konten Carousel pkl 19:00 WIB',
                  skills: ['Optimal Time Dispatch', 'Hashtag Matrix', 'Engagement Monitoring', 'Multi-Platform Sync'],
                  responsibilities: ['Penjadwalan otomatis', 'Monitoring interaksi komentar', 'Pelaporan jangkauan'],
                },
              ],
            },

            // Creative Branch
            {
              id: 'dept-ai-creative',
              name: 'AI Creative & Video Studio',
              title: 'Creative Production (AI)',
              role: 'Creative AI Division',
              type: 'DEPARTMENT',
              category: 'AI',
              department: 'CREATIVE',
              level: 3,
              avatarEmoji: '🎨',
              status: 'ACTIVE',
              score: 98,
              partnerId: 'dept-human-creative',
              partnerName: 'Tim Human Creative',
              description: 'Divisi produksi visual dan video bertenaga AI dengan kepatuhan safe-zone & brand guidelines ketat.',
              children: [
                {
                  id: 'agent-dimas-art',
                  name: 'Dimas Art',
                  title: 'AI Creative Director & Video',
                  role: 'Multi-Format Video & Visual Specialist',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'CREATIVE',
                  level: 4,
                  avatarEmoji: '🎬',
                  status: 'ACTIVE',
                  score: 98,
                  workingHours: '08:00 - 18:00 WIB',
                  partnerId: 'human-andi-design',
                  partnerName: 'Andi Pratama (Creative Lead)',
                  connectedTools: ['OpenAI GPT-4o', 'Gemini 3.7 Flash', 'Imagen 3', 'Creative Studio'],
                  currentTask: 'Render storyboard 4-scene video 9:16 untuk peluncuran produk',
                  skills: ['Video Synthesis', 'Visual Prompt Engineering', 'Color Grading Tokens', 'Multi-Format Export'],
                  responsibilities: ['Sintesis aset video & gambar', 'Pemeriksaan safe-zone visual', 'Generasi storyboard'],
                },
                {
                  id: 'agent-citra-guardian',
                  name: 'Citra Guardian',
                  title: 'AI Brand & Compliance Guardian',
                  role: 'Brand Integrity & WCAG Verification Agent',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'CREATIVE',
                  level: 4,
                  avatarEmoji: '🛡️',
                  status: 'ACTIVE',
                  score: 99,
                  workingHours: '24/7 Autopilot',
                  partnerId: 'human-andi-design',
                  partnerName: 'Andi Pratama (Creative Lead)',
                  connectedTools: ['Brand Kit Engine', 'Claim Filters', 'Palette Verifier'],
                  currentTask: 'Memverifikasi rasio kontras palet warna #10B981 & filter klaim pada materi promosi',
                  skills: ['WCAG AAA Verification', 'Forbidden Claims Detection', 'Typography Enforcer', 'HMAC Validation'],
                  responsibilities: ['Audit visual token brand', 'Pencegahan klaim menyesatkan', 'Quality gate rilis'],
                },
              ],
            },

            // Sales Branch
            {
              id: 'dept-ai-sales',
              name: 'AI Sales & Revenue Pipeline',
              title: 'Sales & CRM (AI)',
              role: 'Sales AI Division',
              type: 'DEPARTMENT',
              category: 'AI',
              department: 'SALES',
              level: 3,
              avatarEmoji: '💼',
              status: 'ACTIVE',
              score: 97,
              partnerId: 'dept-human-sales',
              partnerName: 'Tim Human Sales',
              description: 'Otomatisasi funnel penjualan, respon prospek WhatsApp instan, dan pengelolaan pipeline CRM.',
              children: [
                {
                  id: 'agent-rian-sales',
                  name: 'Rian Sales',
                  title: 'AI Sales & CRM Partner',
                  role: 'WhatsApp Gateway & Deal Specialist',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'SALES',
                  level: 4,
                  avatarEmoji: '💬',
                  status: 'ACTIVE',
                  score: 97,
                  workingHours: '08:00 - 20:00 WIB',
                  partnerId: 'human-doni-sales',
                  partnerName: 'Doni Pratama (Senior AE)',
                  connectedTools: ['WhatsApp Gateway', 'HubSpot CRM', 'Email', 'Google Sheets'],
                  currentTask: 'Menganalisis 42 calon customer & menyiapkan draft follow-up personalisasi via WhatsApp',
                  skills: ['Lead Qualification', 'WhatsApp Conversational Sales', 'Objection Handling', 'Pipeline Analytics'],
                  responsibilities: ['Kualifikasi prospek masuk', 'Draft penawaran harga', 'Pengingat follow-up otomatis'],
                },
              ],
            },

            // Finance Branch
            {
              id: 'dept-ai-finance',
              name: 'AI Finance & CFO Intelligence',
              title: 'Finance & Accounting (AI)',
              role: 'Finance AI Division',
              type: 'DEPARTMENT',
              category: 'AI',
              department: 'FINANCE',
              level: 3,
              avatarEmoji: '📈',
              status: 'ACTIVE',
              score: 98,
              partnerId: 'dept-human-finance',
              partnerName: 'Tim Human Finance',
              description: 'Rekonsiliasi invoice otomatis, proyeksi arus kas, dan pengawasan batas burn rate bisnis.',
              children: [
                {
                  id: 'agent-hendra-cfo',
                  name: 'Hendra CFO',
                  title: 'AI CFO & Financial Modeler',
                  role: 'Cashflow & Unit Economics Modeler',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'FINANCE',
                  level: 4,
                  avatarEmoji: '📊',
                  status: 'ACTIVE',
                  score: 98,
                  workingHours: '08:00 - 18:00 WIB',
                  partnerId: 'human-siti-cfo',
                  partnerName: 'Siti Rahma (Finance Manager)',
                  connectedTools: ['Jurnal / Accurate API', 'Bank BCA API', 'Google Sheets', 'Invoice Vault'],
                  currentTask: 'Rekonsiliasi 128 invoice masuk, analisis cash runway 6 bulan, dan deteksi anomali',
                  skills: ['Cashflow Forecasting', 'Automated Reconciliation', 'Anomaly Detection', 'Unit Economics LTV/CAC'],
                  responsibilities: ['Penyusunan cashflow harian', 'Rekonsiliasi rekening koran', 'Kalkulasi laba kotor'],
                },
              ],
            },

            // HR & Ops Branch
            {
              id: 'dept-ai-hrops',
              name: 'AI HR & Operations Control',
              title: 'People & Operations (AI)',
              role: 'HR & Ops AI Division',
              type: 'DEPARTMENT',
              category: 'AI',
              department: 'HR',
              level: 3,
              avatarEmoji: '⚙️',
              status: 'ACTIVE',
              score: 96,
              partnerId: 'dept-human-hrops',
              partnerName: 'Tim Human HR & Ops',
              description: 'Screening CV kandidat, analisis sentimen kerja karyawan, dan orkestrasi logistik pengiriman.',
              children: [
                {
                  id: 'agent-nadia-hr',
                  name: 'Nadia HR',
                  title: 'AI HR & Talent Coordinator',
                  role: 'Candidate Screening & KPI Specialist',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'HR',
                  level: 4,
                  avatarEmoji: '👥',
                  status: 'ACTIVE',
                  score: 95,
                  workingHours: '08:00 - 18:00 WIB',
                  partnerId: 'human-rina-hr',
                  partnerName: 'Rina Kartika (HR Director)',
                  connectedTools: ['Talent ATS', 'WhatsApp Gateway', 'Attendance System', 'Company Brain'],
                  currentTask: 'Screening 64 CV kandidat teknis dan evaluasi produktivitas mingguan tim',
                  skills: ['Automated Candidate Screening', 'Workforce Sentiment Analysis', 'Policy FAQ', 'KPI Tracking'],
                  responsibilities: ['Penyaringan awal kandidat', 'Onboarding otomatis staff baru', 'Penyusunan rekap absensi'],
                },
                {
                  id: 'agent-bagus-ops',
                  name: 'Bagus Ops',
                  title: 'AI Operations & Logistics Controller',
                  role: 'Process & Restock Automation Agent',
                  type: 'AI_AGENT',
                  category: 'AI',
                  department: 'OPERATIONS',
                  level: 4,
                  avatarEmoji: '📦',
                  status: 'AUTOPILOT',
                  score: 97,
                  workingHours: '24/7 Autopilot',
                  partnerId: 'human-fajar-ops',
                  partnerName: 'Fajar (Operations Lead)',
                  connectedTools: ['WMS Inventory', 'JNE / SiCepat API', 'Telegram', 'Trello'],
                  currentTask: 'Monitoring 210 pengiriman barang dan otomatisasi restock PO buffer stock',
                  skills: ['Inventory Restock Trigger', 'SLA Tracking', 'Courier API Dispatch', 'Process Orchestration'],
                  responsibilities: ['Pemantauan pengiriman pesanan', 'Trigger restock otomatis', 'Eskalasi keterlambatan kurir'],
                },
              ],
            },
          ],
        },

        // ======================== PILLAR 2: HUMAN WORKFORCE ========================
        {
          id: 'pillar-human-workforce',
          name: 'Human Workforce Layer',
          title: 'Human Leadership & Specialists',
          role: 'Human Workforce Division',
          type: 'PILLAR',
          category: 'HUMAN',
          level: 2,
          avatarEmoji: '👥',
          status: 'PAIRED',
          score: 95,
          description: 'Para staf dan pimpinan manusia yang memegang otorisasi strategis, review kualitas, dan persetujuan akhir.',
          skills: ['Strategic Judgment', 'High-Value Empathy', 'Executive Sign-off', 'Creative Disruption'],
          children: [
            // Human Executive
            {
              id: 'dept-human-exec',
              name: 'Human Leadership & Strategy',
              title: 'C-Level & Executive Team',
              role: 'Executive Direction',
              type: 'DEPARTMENT',
              category: 'HUMAN',
              department: 'EXECUTIVE',
              level: 3,
              avatarEmoji: '👔',
              status: 'ACTIVE',
              score: 96,
              children: [
                {
                  id: 'human-ceo-budi',
                  name: 'Budi Santoso',
                  title: 'Chief Executive Officer (CEO)',
                  role: 'Strategic Vision & Final Approver',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'EXECUTIVE',
                  level: 4,
                  avatarEmoji: '🧑‍💼',
                  status: 'ACTIVE',
                  score: 96,
                  workingHours: '08:30 - 18:00 WIB',
                  partnerId: 'node-cos-arya',
                  partnerName: 'Arya (AI Chief of Staff)',
                  connectedTools: ['WhatsApp', 'Dashboard Cockpit', 'Executive Approvals'],
                  currentTask: 'Meninjau laporan pertumbuhan bulanan dan menyetujui anggaran ekspansi',
                  skills: ['Strategic Vision', 'Corporate Governance', 'Capital Allocation', 'Team Leadership'],
                  responsibilities: ['Keputusan final bisnis', 'Kebijakan strategis', 'Evaluasi performa eksekutif'],
                },
              ],
            },

            // Human Marketing
            {
              id: 'dept-human-marketing',
              name: 'Human Marketing & Creative',
              title: 'Marketing & Brand Leaders',
              role: 'Marketing & Creative Leadership',
              type: 'DEPARTMENT',
              category: 'HUMAN',
              department: 'MARKETING',
              level: 3,
              avatarEmoji: '👩‍💼',
              status: 'ACTIVE',
              score: 95,
              children: [
                {
                  id: 'human-maya-mkt',
                  name: 'Maya Wulandari',
                  title: 'Marketing Director',
                  role: 'Brand Compliance & Campaign Approver',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'MARKETING',
                  level: 4,
                  avatarEmoji: '👩‍💼',
                  status: 'ACTIVE',
                  score: 94,
                  workingHours: '09:00 - 17:30 WIB',
                  partnerId: 'agent-kirana-mkt',
                  partnerName: 'Kirana (AI Marketing Strategist)',
                  connectedTools: ['Slack', 'Instagram', 'Trello', 'Creative Studio'],
                  currentTask: 'Review dan persetujuan 8 varian konten media sosial mingguan',
                  skills: ['Brand Identity', 'Campaign Approval', 'Creative Direction', 'Stakeholder Management'],
                  responsibilities: ['Approval konten promosi', 'Kepemimpinan tim promosi', 'Supervisi brand compliance'],
                },
                {
                  id: 'human-andi-design',
                  name: 'Andi Pratama',
                  title: 'Creative & Visual Lead',
                  role: 'Art Direction & Video Approver',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'CREATIVE',
                  level: 4,
                  avatarEmoji: '🎨',
                  status: 'ACTIVE',
                  score: 95,
                  workingHours: '09:00 - 18:00 WIB',
                  partnerId: 'agent-dimas-art',
                  partnerName: 'Dimas Art (AI Creative Director)',
                  connectedTools: ['Figma', 'Creative Studio', 'Adobe CC'],
                  currentTask: 'Approval storyboard video 9:16 dan kurasi aset visual produk',
                  skills: ['Art Direction', 'Motion Design Oversight', 'Visual QA', 'Typography Curating'],
                  responsibilities: ['Persetujuan final aset desain', 'Pengarahan gaya visual', 'Kualitas output video'],
                },
              ],
            },

            // Human Sales & Ops
            {
              id: 'dept-human-salesops',
              name: 'Human Sales, Finance & Ops',
              title: 'Revenue, Finance & Operations Leaders',
              role: 'Business Execution Leaders',
              type: 'DEPARTMENT',
              category: 'HUMAN',
              department: 'SALES',
              level: 3,
              avatarEmoji: '💼',
              status: 'ACTIVE',
              score: 96,
              children: [
                {
                  id: 'human-doni-sales',
                  name: 'Doni Pratama',
                  title: 'Senior Account Executive',
                  role: 'High-Value Deal Closing & Relationship Lead',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'SALES',
                  level: 4,
                  avatarEmoji: '🧑‍💼',
                  status: 'ACTIVE',
                  score: 95,
                  workingHours: '08:30 - 17:30 WIB',
                  partnerId: 'agent-rian-sales',
                  partnerName: 'Rian Sales (AI Sales Partner)',
                  connectedTools: ['WhatsApp', 'CRM Mobile', 'Zoom'],
                  currentTask: 'Meeting negosiasi kontrak enterprise dengan 3 klien B2B utama',
                  skills: ['High-Value Negotiation', 'Relationship Building', 'Deal Closing', 'Contract Structuring'],
                  responsibilities: ['Penutupan deal enterprise', 'Pertemuan tatap muka klien', 'Persetujuan diskon khusus'],
                },
                {
                  id: 'human-siti-cfo',
                  name: 'Siti Rahma',
                  title: 'Finance & Tax Manager',
                  role: 'Fiscal Compliance & Budget Authorizer',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'FINANCE',
                  level: 4,
                  avatarEmoji: '👩‍💼',
                  status: 'ACTIVE',
                  score: 96,
                  workingHours: '08:30 - 17:00 WIB',
                  partnerId: 'agent-hendra-cfo',
                  partnerName: 'Hendra CFO (AI CFO Modeler)',
                  connectedTools: ['Internet Banking', 'Tax Portal', 'Financial Approvals'],
                  currentTask: 'Persetujuan transfer pembayaran vendor dan validasi laporan SPT masa PPN',
                  skills: ['Tax Compliance', 'Audit Oversight', 'Cashflow Authorization', 'Budget Governance'],
                  responsibilities: ['Otorisasi pencairan dana', 'Kepatuhan pajak negara', 'Pemeriksaan audit eksternal'],
                },
                {
                  id: 'human-rina-hr',
                  name: 'Rina Kartika',
                  title: 'HR & People Director',
                  role: 'People Strategy & Final Interview Lead',
                  type: 'HUMAN_EMPLOYEE',
                  category: 'HUMAN',
                  department: 'HR',
                  level: 4,
                  avatarEmoji: '👩‍💼',
                  status: 'ACTIVE',
                  score: 95,
                  workingHours: '09:00 - 17:00 WIB',
                  partnerId: 'agent-nadia-hr',
                  partnerName: 'Nadia HR (AI HR Coordinator)',
                  connectedTools: ['ATS Portal', 'People HRMS', 'Interview Room'],
                  currentTask: 'Wawancara final untuk posisi Tech Lead & persetujuan offer letter',
                  skills: ['Executive Interviewing', 'Compensation Design', 'Culture Governance', 'Conflict Resolution'],
                  responsibilities: ['Keputusan hiring final', 'Evaluasi budaya kerja', 'Kebijakan kompensasi'],
                },
              ],
            },
          ],
        },

        // ======================== PILLAR 3: BUSINESS ECOSYSTEM & TOOLS ========================
        {
          id: 'pillar-ecosystem-tools',
          name: 'Business Ecosystem & Tools',
          title: 'Integrations, Workflows & Data',
          role: 'Connected Infrastructure',
          type: 'PILLAR',
          category: 'ECOSYSTEM',
          level: 2,
          avatarEmoji: '⚡',
          status: 'ACTIVE',
          score: 99,
          description: 'Jaringan integrasi komunikasi, penyimpanan data, API pihak ketiga, dan saluran komunikasi bisnis.',
          skills: ['Live Webhooks', 'OAuth 2.0 Auth', 'Real-Time Sync', 'Audit Telemetry'],
          children: [
            {
              id: 'dept-eco-comms',
              name: 'Communication Gateways',
              title: 'Omnichannel Chat & Gateways',
              role: 'Communication Rail',
              type: 'DEPARTMENT',
              category: 'ECOSYSTEM',
              level: 3,
              avatarEmoji: '💬',
              status: 'ACTIVE',
              children: [
                {
                  id: 'tool-whatsapp',
                  name: 'WhatsApp Business API',
                  title: 'Conversational Sales & Staff Gateway',
                  role: 'Bi-directional Chat Gateway',
                  type: 'TOOL',
                  category: 'ECOSYSTEM',
                  level: 4,
                  avatarEmoji: '🟢',
                  status: 'ACTIVE',
                  score: 99,
                  description: 'Karyawan dan pimpinan mengirim instruksi suara/teks ke AI, serta menerima notifikasi approval via WhatsApp.',
                  connectedTools: ['Meta Cloud API', 'Webhook Engine'],
                  skills: ['Instant Message Sync', 'Voice Note Transcribing', 'Media Delivery', '2-Way Webhook'],
                  responsibilities: ['Relay instruksi instan', 'Pemberitahuan approval', 'Interaksi customer'],
                },
                {
                  id: 'tool-telegram-slack',
                  name: 'Telegram & Slack Relay',
                  title: 'Internal Team Collaboration Rail',
                  role: 'Real-time Bot Notification',
                  type: 'TOOL',
                  category: 'ECOSYSTEM',
                  level: 4,
                  avatarEmoji: '✈️',
                  status: 'ACTIVE',
                  score: 99,
                  description: 'Notifikasi status pekerjaan dan log tugas terkirim otomatis ke channel tim Telegram & Slack.',
                  connectedTools: ['Slack Bot API', 'Telegram Bot API'],
                  skills: ['Channel Broadcast', 'Threaded Replies', 'Slash Commands'],
                  responsibilities: ['Broadcast hasil kerja AI', 'Log operasional tim', 'Alert darurat'],
                },
              ],
            },
            {
              id: 'dept-eco-storage',
              name: 'Workspace & Cloud Data',
              title: 'Document, Spreadsheet & Task Tools',
              role: 'Productivity Infrastructure',
              type: 'DEPARTMENT',
              category: 'ECOSYSTEM',
              level: 3,
              avatarEmoji: '📂',
              status: 'ACTIVE',
              children: [
                {
                  id: 'tool-google-workspace',
                  name: 'Google Workspace & Trello',
                  title: 'Docs, Sheets & Board Sync',
                  role: 'Cloud Productivity Rail',
                  type: 'TOOL',
                  category: 'ECOSYSTEM',
                  level: 4,
                  avatarEmoji: '📊',
                  status: 'ACTIVE',
                  score: 99,
                  description: 'AI membaca SOP di Google Docs, mengisi rekonsiliasi di Google Sheets, dan memperbarui kartu tugas Trello.',
                  connectedTools: ['Google Drive API', 'Google Sheets API', 'Trello REST API'],
                  skills: ['Sheet Cell Manipulation', 'Document Ingestion', 'Kanban Board Sync'],
                  responsibilities: ['Penyimpanan laporan resmi', 'Sinkronisasi papan Trello', 'Arsip bukti transfer'],
                },
                {
                  id: 'tool-company-brain',
                  name: 'Company Brain Vector Vault',
                  title: 'Enterprise Knowledge & SOP RAG',
                  role: 'Persistent Memory Core',
                  type: 'TOOL',
                  category: 'ECOSYSTEM',
                  level: 4,
                  avatarEmoji: '🧠',
                  status: 'ACTIVE',
                  score: 99,
                  description: 'Basis pengetahuan terpusat berisi SOP, pedoman merek, dan riwayat keputusan bisnis yang aman & terenkripsi.',
                  connectedTools: ['pgvector Storage', 'Semantic Embeddings', 'AES-256 Vault'],
                  skills: ['Semantic Retrieval', 'Zero-Data-Leak RAG', 'Versioned SOP Indexing'],
                  responsibilities: ['Menyimpan SOP perusahaan', 'RAG query berkecepatan tinggi', 'Audit izin akses dokumen'],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

// Flatten helper for search, filters, and list views
export function flattenWorkforceTree(node: WorkforceTreeNode): WorkforceTreeNode[] {
  const result: WorkforceTreeNode[] = [node];
  if (node.children) {
    for (const child of node.children) {
      result.push(...flattenWorkforceTree(child));
    }
  }
  return result;
}

export const ALL_WORKFORCE_NODES = flattenWorkforceTree(WORKFORCE_TREE_DATA);
