apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-svc
  namespace: orchestreeai-admin
  labels:
    app: admin-dashboard
spec:
  type: ClusterIP
  selector:
    app: admin-dashboard
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
